test:
  adapter: sqlite3
  database: db/api_test.sqlite3
  host: localhost
  pool: 5
  username: 
  password:

development:
  adapter: sqlite3
  database: db/iapi_dev.sqlite3
  host: localhost
  pool: 5
  username: 
  password:
